// GENERATED by kairos-export-contracts from kairos_contracts v0.14.0. Do not edit.
export const CONTRACT_VERSION = "0.14.0";

export const EventType = {
  TASK_CREATED: "task.created",
  TASK_STATUS_CHANGED: "task.status_changed",
  TASK_COMPLETED: "task.completed",
  TASK_FAILED: "task.failed",
  PROCESS_SPAWNED: "process.spawned",
  PROCESS_STATE_CHANGED: "process.state_changed",
  PROCESS_CHECKPOINTED: "process.checkpointed",
  PROCESS_USAGE: "process.usage",
  AGENT_LOG: "agent.log",
  SYSCALL_REQUESTED: "syscall.requested",
  SYSCALL_DECIDED: "syscall.decided",
  SYSCALL_COMPLETED: "syscall.completed",
  APPROVAL_REQUESTED: "approval.requested",
  APPROVAL_RESOLVED: "approval.resolved",
  TRANSACTION_COMMITTED: "transaction.committed",
  TRANSACTION_ROLLED_BACK: "transaction.rolled_back",
  POLICY_UPDATED: "policy.updated",
  AUDIT_APPENDED: "audit.appended",
  IPC_MESSAGE: "ipc.message",
  KNOWLEDGE_CHANGED: "knowledge.changed",
  KNOWLEDGE_REINDEXED: "knowledge.reindexed",
  KNOWLEDGE_RETRIEVED: "knowledge.retrieved",
  INGEST_PROGRESS: "ingest.progress",
  MOUNT_SYNCED: "mount.synced",
  CONNECTOR_CHANGED: "connector.changed",
  MEMORY_INVALIDATED: "memory.invalidated",
  MEMORY_CONSOLIDATED: "memory.consolidated",
  MODEL_INVOKED: "model.invoked",
  SANDBOX_STARTED: "sandbox.started",
  SANDBOX_DESTROYED: "sandbox.destroyed",
  SANDBOX_SCREENSHOT: "sandbox.screenshot",
  TOOL_STARTED: "tool.started",
  TOOL_COMPLETED: "tool.completed",
  SYSTEM_READY: "system.ready",
  SYSTEM_HEALTH: "system.health",
  CRON_TRIGGERED: "cron.triggered",
  TASK_UNDERSTOOD: "task.understood",
  AGENT_PLANNED: "agent.planned",
  AGENT_CREATED: "agent.created",
  AGENT_THOUGHT: "agent.thought",
  TOOL_QUERY: "tool.query",
  TASK_DATA: "task.data",
} as const;
export type EventTypeValue = (typeof EventType)[keyof typeof EventType];

export const ALLOWED_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["INITIALIZING", "TERMINATED"],
  INITIALIZING: ["FAILED", "READY", "TERMINATED"],
  READY: ["RUNNING", "TERMINATED"],
  RUNNING: ["CHECKPOINTING", "COMPLETED", "FAILED", "PAUSED", "TERMINATED", "WAITING"],
  WAITING: ["RUNNING", "TERMINATED"],
  PAUSED: ["RUNNING", "TERMINATED"],
  CHECKPOINTING: ["FAILED", "RUNNING"],
  FAILED: ["RETRYING", "TERMINATED"],
  RETRYING: ["RUNNING", "TERMINATED"],
  COMPLETED: [],
  TERMINATED: [],
};

export const USER_HEADER = "X-Kairos-User";
export const ORG_HEADER = "X-Kairos-Org";
export const WS_EVENTS_PATH = "/ws/events";
