"""Regenerate the language-neutral artifacts from the Python contracts:

    shared/schemas/<Model>.json      one JSON Schema per exported model
    shared/schemas/kairos.schema.json  bundle of all models ($defs) — input for TypeScript generation
    shared/fixtures/json/<name>.json   example payloads from examples.py
    shared/api/openapi.json          gateway OpenAPI (from the mock gateway, needs the [api] extra)

Run after every contract change:  uv run --package kairos-contracts kairos-export-contracts
then (optional, needs Node):       npm --prefix shared/ts run generate
"""
from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, TypeAdapter

from . import CONTRACT_VERSION, examples
from .schema import EXPORTED_MODELS
from .wiring import REPO_ROOT

SHARED = REPO_ROOT / "shared"


def _write(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, default=str) + "\n", encoding="utf-8", newline="\n")  # LF on every OS


def export_schemas() -> int:
    out = SHARED / "schemas"
    bundle: dict = {"$schema": "https://json-schema.org/draft/2020-12/schema", "title": "KAIROS",
                    "description": f"KAIROS contracts v{CONTRACT_VERSION}", "type": "object", "$defs": {}}
    for model in EXPORTED_MODELS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        _write(out / f"{model.__name__}.json", schema)
        for name, d in schema.pop("$defs", {}).items():
            bundle["$defs"][name] = d
        if set(schema) != {"$ref"}:  # recursive models are emitted as {"$ref": ...} + $defs
            bundle["$defs"][model.__name__] = schema
    # field-level "title"s make json2ts emit one alias per field (TaskId14...). Keep titles on models only.
    # A "properties" mapping is keyed by field name, so a field called "title" must survive there.
    def strip_titles(node: object, keep: bool, field_map: bool = False) -> None:
        if isinstance(node, dict):
            if not keep and not field_map:
                node.pop("title", None)
            for k, v in node.items():
                strip_titles(v, keep=False, field_map=(k == "properties" and not field_map))
        elif isinstance(node, list):
            for v in node:
                strip_titles(v, keep=False)

    for d in bundle["$defs"].values():
        strip_titles(d, keep=True)
    # expose every model as a property so json-schema-to-typescript emits them all
    bundle["properties"] = {n: {"$ref": f"#/$defs/{n}"} for n in sorted(bundle["$defs"])}
    _write(out / "kairos.schema.json", bundle)
    return len(EXPORTED_MODELS)


def export_fixtures() -> int:
    out = SHARED / "fixtures" / "json"
    for name, fn in examples.ALL_EXAMPLES.items():
        value = fn()
        adapter = TypeAdapter(type(value)) if isinstance(value, BaseModel) else None
        if isinstance(value, list):
            data = [v.model_dump(mode="json") for v in value]
        else:
            data = adapter.dump_python(value, mode="json") if adapter else value
        _write(out / f"{name}.json", data)
    return len(examples.ALL_EXAMPLES)


def export_ts_constants() -> None:
    """Runtime constants the UI needs (types come from kairos.d.ts, generated by json-schema-to-typescript)."""
    from .schema import ALLOWED_TRANSITIONS, EventType

    lines = [
        f"// GENERATED by kairos-export-contracts from kairos_contracts v{CONTRACT_VERSION}. Do not edit.",
        f'export const CONTRACT_VERSION = "{CONTRACT_VERSION}";',
        "",
        "export const EventType = {",
        *[f'  {e.name}: "{e.value}",' for e in EventType],
        "} as const;",
        "export type EventTypeValue = (typeof EventType)[keyof typeof EventType];",
        "",
        "export const ALLOWED_TRANSITIONS: Record<string, string[]> = {",
        *[f'  {s.value}: [{", ".join(repr(d.value).replace(chr(39), chr(34)) for d in sorted(ds))}],'
          for s, ds in ALLOWED_TRANSITIONS.items()],
        "};",
        "",
        'export const USER_HEADER = "X-Kairos-User";',
        'export const ORG_HEADER = "X-Kairos-Org";',
        'export const WS_EVENTS_PATH = "/ws/events";',
        "",
    ]
    path = SHARED / "ts" / "src" / "constants.ts"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def export_openapi() -> bool:
    try:
        from .api.mock_gateway import build_mock_app
    except ImportError:
        print("  (skipped openapi.json: install the [api] extra)")
        return False
    _write(SHARED / "api" / "openapi.json", build_mock_app().openapi())
    return True


def main() -> None:
    print(f"KAIROS contracts v{CONTRACT_VERSION}")
    print(f"  schemas : {export_schemas()} models -> shared/schemas/")
    print(f"  fixtures: {export_fixtures()} examples -> shared/fixtures/json/")
    export_ts_constants()
    print("  ts      : shared/ts/src/constants.ts  (run `npm --prefix shared/ts run generate` for types)")
    if export_openapi():
        print("  openapi : shared/api/openapi.json")


if __name__ == "__main__":
    main()
